#!/usr/bin/env bash
# Regenerate lock/constraints.txt, the GENERATED transitive-pin lock of the workspace image
# (ADR-012 amendment). Run it whenever a workspace pin in versions.env changes, and commit
# the result. It resolves requirements.in fresh (no lock), freezes the result, and drops the
# top-level packages, whose pins live in versions.env.
#
#   v3/images/workspace/relock.sh
#
# Builds through `docker compose` (like the lab itself), so it works without buildx.
set -euo pipefail
here=$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)
v3=$(cd -P "$here/../.." && pwd)
name=$(basename "$here")
tag="lakehouse-lab/v3-${name}:relock"

ctx=$(mktemp -d)
trap 'rm -rf "$ctx"' EXIT
cp -R "$here/." "$ctx/image/"
: >"$ctx/image/lock/constraints.txt"

# Every ARG the Dockerfile declares, valued from versions.env (and pending .pins/*.env).
{
  echo "services:"
  echo "  relock:"
  echo "    image: ${tag}"
  echo "    build:"
  echo "      context: ./image"
  [ -d "$v3/starter" ] && printf '      additional_contexts:\n        starter: %s\n' "$v3/starter"
  echo "      args:"
  sed -n 's/^[[:space:]]*ARG[[:space:]]\+\([A-Za-z_][A-Za-z0-9_]*\).*/\1/p' "$here/Dockerfile" | sort -u |
    while read -r arg; do
      val=$(cat "$v3/versions.env" "$v3"/.pins/*.env 2>/dev/null | sed -n "s/^${arg}=//p" | tail -n 1)
      [ -n "$val" ] || { echo "relock: ARG $arg has no value in versions.env" >&2; exit 1; }
      printf '        %s: "%s"\n' "$arg" "$val"
    done
} >"$ctx/compose.yaml"
docker compose -p "v3-relock-${name}" -f "$ctx/compose.yaml" build -q relock

tops=$(sed -e 's/#.*//' -e 's/\[.*//' -e 's/=.*//' "$here/requirements.in" | tr 'A-Z_' 'a-z-' \
  | grep -v '^$' | sed 's/-/[-_.]/g' | paste -sd'|')
{
  echo "# GENERATED by images/${name}/relock.sh: transitive pins for the ${name} image. Do not edit."
  docker run --rm --network none --entrypoint pip "$tag" list --format=freeze \
    | grep -v -i -E "^(${tops})==" | grep -v -E '^(pip|setuptools|wheel)=='
} >"$here/lock/constraints.txt"
docker image rm "$tag" >/dev/null
echo "images/${name}/lock/constraints.txt: $(grep -vc '^#' "$here/lock/constraints.txt") pins"
