#!/usr/bin/env bash
# Build the workspace image on the server. Run from the spike dir.
#   ./build.sh            build (cached) with lock/constraints.txt
#   ./build.sh --relock   resolve fresh from requirements.in, then rewrite lock/constraints.txt
#   ./build.sh --no-cache full rebuild (reproducibility check)
#   ./build.sh --classic  also build the OQ-2 classic-driver comparison image
set -euo pipefail
cd "$(dirname "$0")"
dc() { docker compose -p v3-s4 --env-file ../versions.env --env-file versions.local.env "$@"; }

opts=(); classic=0; relock=0
for a in "$@"; do
  case "$a" in
    --relock) relock=1 ;;
    --no-cache) opts+=(--no-cache) ;;
    --classic) classic=1 ;;
  esac
done

if [ "$relock" = 1 ]; then
  : > lock/constraints.txt
  dc build "${opts[@]}" workspace
  # Freeze everything, drop the top-level packages (their pins live in versions*.env).
  tops=$(sed -e 's/#.*//' -e 's/\[.*//' -e 's/=.*//' requirements.in | tr 'A-Z_' 'a-z-' | grep -v '^$' | sed 's/-/[-_.]/g' | paste -sd'|')
  docker run --rm --network none --entrypoint pip lakehouse-workspace:v3-s4-spike freeze --all \
    | grep -v -E "^(${tops})==" -i \
    | grep -v -E '^(pip|setuptools|wheel)==' > lock/constraints.new
  { echo "# GENERATED by build.sh --relock: transitive pins for the workspace image. Do not edit."; cat lock/constraints.new; } > lock/constraints.txt
  rm lock/constraints.new
  echo "lock/constraints.txt: $(grep -vc '^#' lock/constraints.txt) pins"
fi
dc build "${opts[@]}" workspace
if [ "$classic" = 1 ]; then dc --profile classic build workspace-classic; fi
docker image ls --format '{{.Repository}}:{{.Tag}} {{.Size}}' | grep lakehouse-workspace
