icon: "fas fa-database"
header: true

theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    background: "#f5f5f5"
    text: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    background: "#2b2b2b"
    text: "#eaeaea"

footer: '<p>Lakehouse Lab v2.0 - Issues Resolved | DuckDB 1.3.0 + duckdb-engine 0.17.0</p>'

message:
  style: "is-success"
  title: "✅ All Issues Fixed!"
  icon: "fa fa-check-circle"
  content: "Your lakehouse is ready with all issues resolved:<br />✅ <strong>Issue #1</strong>: Superset S3 configuration now persistent<br />✅ <strong>Issue #2</strong>: Airflow DuckDB imports working<br />🚀 <strong>Latest tech</strong>: DuckDB 1.3.0 + duckdb-engine 0.17.0"

services:
  - name: "Analytics & BI - ✅ Fixed"
    icon: "fas fa-chart-line"
    items:
      - name: "Superset (Issue #1 Fixed)"
        icon: "fas fa-chart-bar"
        subtitle: "BI & Visualization - S3 config now persistent!"
        tag: "fixed"
        url: "http://localhost:9030"
        target: "_blank"

      - name: "JupyterLab (DuckDB 1.3.0)"
        icon: "fas fa-book"
        subtitle: "Data Science - Latest DuckDB packages installed"
        tag: "updated"
        url: "http://localhost:9040"
        target: "_blank"

  - name: "Orchestration - ✅ Fixed"
    icon: "fas fa-cogs"
    items:
      - name: "Airflow (Issue #2 Fixed)"
        icon: "fas fa-tachometer-alt"
        subtitle: "Workflow Orchestration - DuckDB imports working!"
        tag: "fixed"
        url: "http://localhost:9020"
        target: "_blank"

  - name: "Storage & Infrastructure"
    icon: "fas fa-server"
    items:
      - name: "MinIO Console"
        icon: "fas fa-cloud"
        subtitle: "S3-Compatible Object Storage"
        tag: "storage"
        url: "http://localhost:9001"
        target: "_blank"

      - name: "Spark Master"
        icon: "fas fa-fire"
        subtitle: "Distributed Data Processing Engine"
        tag: "compute"
        url: "http://localhost:8080"
        target: "_blank"

      - name: "Portainer"
        icon: "fas fa-docker"
        subtitle: "Container Management & Monitoring"
        tag: "monitoring"
        url: "http://localhost:9060"
        target: "_blank"

links:
  - name: "Local Services"
    icon: "fas fa-home"
    url: "http://localhost:9061"
    target: "_self"
  
  - name: "Test Health"
    icon: "fas fa-heartbeat"
    url: "#"
    target: "_self"
