#!/usr/bin/env bash
# Regenerate lock/requirements.txt, the GENERATED full dependency lock of the ai-gateway image
# (ADR-012 amendment). Run it whenever LITELLM_VERSION or PRISMA_PYTHON_VERSION changes, and
# commit the result:
#
#   v3/images/ai-gateway/relock.sh
#
# It resolves requirements.in with pip's resolver (`pip install --dry-run --report`, nothing is
# installed) in the pinned Python base image, then writes every resolved package EXCEPT the
# ones on the exclusion list below. The image installs this lock with `--no-deps`, so the
# excluded packages are never downloaded at build time and never ship in the image.
#
# Excluded, and why (Phase 5 contract: "use only features available in its open-source
# license"):
#   litellm-enterprise  LicenseRef-Proprietary (BerriAI Enterprise License: production use
#                       needs a subscription; redistribution forbidden). The `litellm[proxy]`
#                       extra requires it, but the proxy imports it optionally (ImportError =
#                       enterprise features off).
# The script also FAILS if any other resolved package declares a proprietary license, so a
# new proprietary dependency cannot slip into the public image through a version bump.
set -euo pipefail
here=$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)
v3=$(cd -P "$here/../.." && pwd)

val() {  # versions.env, then pending pins (the last assignment wins)
  cat "$v3/versions.env" "$v3"/.pins/*.env 2>/dev/null | sed -n "s/^$1=//p" | tail -n 1
}
tag=$(val PYTHON_IMAGE_TAG) digest=$(val PYTHON_IMAGE_DIGEST)
[ -n "$tag" ] && [ -n "$digest" ] || { echo "relock: PYTHON_IMAGE_TAG/DIGEST missing" >&2; exit 1; }
args=()
for v in $(grep -o '\${[A-Z0-9_]*}' "$here/requirements.in" | tr -d '${}' | sort -u); do
  x=$(val "$v")
  [ -n "$x" ] || { echo "relock: $v has no value in versions.env or .pins/" >&2; exit 1; }
  args+=(-e "$v=$x")
done

docker run --rm -i "${args[@]}" -v "$here:/work:ro" --entrypoint python3 \
  "python:${tag}@${digest}" - >"$here/lock/requirements.txt.new" <<'PY'
import json, os, subprocess, sys, tempfile
EXCLUDE = {"litellm-enterprise"}
req = os.path.expandvars(open("/work/requirements.in").read())
with tempfile.TemporaryDirectory() as d:
    with open(f"{d}/req.txt", "w") as f:
        f.write(req)
    subprocess.run([sys.executable, "-m", "pip", "install", "--quiet", "--disable-pip-version-check",
                    "--dry-run", "--ignore-installed", "--report", f"{d}/report.json",
                    "-r", f"{d}/req.txt"], check=True, stdout=sys.stderr)
    report = json.load(open(f"{d}/report.json"))
pins, bad = [], []
for item in report["install"]:
    md = item["metadata"]
    name = md["name"].lower().replace("_", "-")
    lic = " ".join(str(md.get(k) or "") for k in ("license_expression", "license"))
    lic += " " + " ".join(c for c in md.get("classifier", []) if "License" in c)
    if name in EXCLUDE:
        print(f"relock: excluded {name}=={md['version']} ({lic.strip() or 'no license field'})", file=sys.stderr)
        continue
    if "proprietary" in lic.lower():
        bad.append(f"{name}=={md['version']} ({lic.strip()})")
    pins.append(f"{name}=={md['version']}")
if bad:
    sys.exit("relock: proprietary package(s) in the resolved set: " + ", ".join(bad))
print("# GENERATED by images/ai-gateway/relock.sh: every package of the ai-gateway image. Do not edit.")
print("# Installed with --no-deps. Excluded on purpose: " + ", ".join(sorted(EXCLUDE)) + " (proprietary).")
print("\n".join(sorted(pins)))
PY
mv "$here/lock/requirements.txt.new" "$here/lock/requirements.txt"
echo "images/ai-gateway/lock/requirements.txt: $(grep -vc '^#' "$here/lock/requirements.txt") pins"
