"""Build-time check of the ai-gateway image (run by the Dockerfile; exits non-zero on failure).

* The installed litellm / prisma match versions.env (the lock is regenerated by relock.sh;
  a stale lock fails the build instead of shipping other versions).
* No proprietary LiteLLM code is present: neither the `litellm-enterprise` distribution nor
  an importable `litellm_enterprise` / `enterprise` module.
* The prisma client is generated and its engines live under /opt/prisma (no runtime download).
"""
import importlib.metadata as md
import importlib.util
import sys

want_litellm, want_prisma, stage = sys.argv[1], sys.argv[2], sys.argv[3]
errors = []
for dist, want in (("litellm", want_litellm), ("prisma", want_prisma)):
    have = md.version(dist)
    if have != want:
        errors.append(f"{dist} {have} installed, versions.env says {want} (run images/ai-gateway/relock.sh)")
for dist in ("litellm-enterprise", "litellm_enterprise"):
    try:
        md.version(dist)
        errors.append(f"proprietary distribution {dist} is installed")
    except md.PackageNotFoundError:
        pass
for mod in ("litellm_enterprise", "enterprise"):
    if importlib.util.find_spec(mod) is not None:
        errors.append(f"proprietary module {mod} is importable")
for dist in md.distributions():
    meta = dist.metadata
    lic = " ".join(filter(None, [meta.get("License-Expression"), meta.get("License")]))
    if "proprietary" in lic.lower():
        errors.append(f"{meta['Name']} declares a proprietary license: {lic}")
if stage == "runtime":
    from prisma.client import BINARY_PATHS  # generated by `prisma generate`

    paths = list(BINARY_PATHS.query_engine.values())
    if not paths or not all(p.startswith("/opt/prisma/") for p in paths):
        errors.append(f"prisma query engine not under /opt/prisma: {paths}")
if errors:
    sys.exit("ai-gateway image check failed:\n  " + "\n  ".join(errors))
print(f"ai-gateway image check ({stage}): litellm {want_litellm}, prisma {want_prisma}, no proprietary packages")
