---
# Lakehouse Lab Services Configuration for Homepage
# This file defines all the services displayed on the Homepage dashboard

- Lakehouse Core:
    - Spark Master:
        icon: apache.png
        href: http://${HOMEPAGE_VAR_HOST_IP}:8080
        description: Distributed Computing Engine
        widget:
          type: customapi
          url: http://spark-master:8080/json
          
    - PostgreSQL:
        icon: postgres.png
        href: http://${HOMEPAGE_VAR_HOST_IP}:5432
        description: Analytics Database
        
    - MinIO Console:
        icon: minio.png
        href: http://${HOMEPAGE_VAR_HOST_IP}:9001
        description: Object Storage (S3-Compatible)
        widget:
          type: customapi
          url: http://minio:9000/minio/health/live

- Analytics & BI:
    - Apache Airflow:
        icon: airflow.png
        href: http://${HOMEPAGE_VAR_HOST_IP}:9020
        description: Workflow Orchestration
        widget:
          type: customapi
          url: http://airflow-webserver:8080/health
          
    - Apache Superset:
        icon: superset.png
        href: http://${HOMEPAGE_VAR_HOST_IP}:9030
        description: Business Intelligence & Dashboards
        widget:
          type: customapi
          url: http://superset:8088/health
          
    - Vizro:
        icon: plotly.png
        href: http://${HOMEPAGE_VAR_HOST_IP}:9050
        description: Interactive Dashboards

- Development & ML:
    - JupyterLab:
        icon: jupyter.png
        href: http://${HOMEPAGE_VAR_HOST_IP}:9040
        description: Data Science Notebooks
        widget:
          type: customapi
          url: http://jupyter:8888/api/status
          
    - LanceDB:
        icon: database.png
        href: http://${HOMEPAGE_VAR_HOST_IP}:9080
        description: Vector Database for AI/ML
        widget:
          type: customapi
          url: http://lancedb:8000/health

- Management:
    - Portainer:
        icon: portainer.png
        href: http://${HOMEPAGE_VAR_HOST_IP}:9060
        description: Docker Container Management
        widget:
          type: portainer
          url: http://portainer:9000
          env: 2