---
# Homepage Settings Configuration for Lakehouse Lab

title: "{{HOMEPAGE_VAR_TITLE}}"
favicon: https://raw.githubusercontent.com/gethomepage/homepage/main/public/android-chrome-192x192.png

theme: dark
color: slate

layout:
  Lakehouse Core:
    style: row
    columns: 3
  Analytics & BI:
    style: row
    columns: 3
  Development & ML:
    style: row
    columns: 2
  Management:
    style: row
    columns: 2

headerStyle: "{{HOMEPAGE_VAR_HEADER_STYLE}}"
hideVersion: "{{HOMEPAGE_VAR_HIDEVERSION}}"

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true

providers:
  openweathermap: false
  weatherapi: false

language: en
target: _self

background:
  image: ""
  blur: ""
  saturate: ""
  brightness: ""
  opacity: ""

cardBlur: ""

backgroundOpacity: ""