# shellcheck shell=bash
# .secrets.env generation (CONTRACT.md runtime contract).
# - CSPRNG only: openssl rand, or /dev/urandom. Never $RANDOM (ISSUE_WEAK_CREDENTIAL_RNG).
# - Every generated value is URL-safe ([A-Za-z0-9] or hex), so it can sit in a JDBC/DSN
#   URL unescaped (INV_DB_PASSWORDS_URL_SAFE). The STS signing key is base64 by format
#   and is never used in a URL.
# - Existing values are never changed: re-running only fills in missing keys, because
#   databases and Keycloak keep the password they were first initialised with.

# rand_hex BYTES -> 2*BYTES hex chars
rand_hex() {
  local n=${1:-24} out=""
  if command -v openssl >/dev/null 2>&1; then
    out=$(openssl rand -hex "$n" 2>/dev/null) || out=""
  fi
  if [ -z "$out" ]; then
    out=$(head -c "$n" /dev/urandom | od -An -v -tx1 | tr -d ' \n')
  fi
  [ "${#out}" -eq $((n * 2)) ] || die "CSPRNG failure (rand_hex)"
  printf '%s\n' "$out"
}

# rand_alnum LEN -> LEN chars of [A-Za-z0-9], from /dev/urandom (rejection sampling via tr).
rand_alnum() {
  local n=${1:-24} out
  out=$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom 2>/dev/null | head -c "$n") || true
  [ "${#out}" -eq "$n" ] || die "CSPRNG failure (rand_alnum)"
  printf '%s\n' "$out"
}

# rand_b64 BYTES -> standard base64 of BYTES random bytes
rand_b64() {
  local n=${1:-32} out
  if command -v openssl >/dev/null 2>&1; then
    out=$(openssl rand -base64 "$n" 2>/dev/null | tr -d '\n') || out=""
  fi
  [ -n "${out:-}" ] || out=$(head -c "$n" /dev/urandom | base64 | tr -d '\n')
  printf '%s\n' "$out"
}

# secret_spec -> "KEY generator" lines. Order is the order written to a new file.
secret_spec() {
  cat <<'EOF'
POSTGRES_PASSWORD hex24
KEYCLOAK_DB_PASSWORD hex24
LAKEKEEPER_DB_PASSWORD hex24
KC_ADMIN_USER kcadmin
KC_ADMIN_PASSWORD alnum24
LAB_ADMIN_USER labadmin
LAB_ADMIN_PASSWORD alnum20
SEAWEEDFS_ADMIN_ACCESS_KEY accesskey
SEAWEEDFS_ADMIN_SECRET_KEY alnum40
SEAWEEDFS_STS_SIGNING_KEY b64_32
LAKEKEEPER_PG_ENCRYPTION_KEY alnum40
OIDC_CLIENT_SECRET_TRINO alnum32
OIDC_CLIENT_SECRET_LAKEKEEPER alnum32
OIDC_CLIENT_SECRET_CONSOLE alnum32
TRINO_INTERNAL_SECRET hex32
LAB_TEST_USER_PASSWORD alnum16
EOF
}

gen_value() {
  case "$1" in
    hex24)     rand_hex 24 ;;
    hex32)     rand_hex 32 ;;
    alnum16)   rand_alnum 16 ;;
    alnum20)   rand_alnum 20 ;;
    alnum24)   rand_alnum 24 ;;
    alnum32)   rand_alnum 32 ;;
    alnum40)   rand_alnum 40 ;;
    b64_32)    rand_b64 32 ;;
    accesskey) printf 'LAB%s\n' "$(rand_alnum 17 | tr '[:lower:]' '[:upper:]')" ;;
    # Usernames, not secrets. Overridable with --admin-user (LAB_ADMIN_USER).
    kcadmin)   printf '%s\n' "kcadmin" ;;
    labadmin)  printf '%s\n' "${LAB_ADMIN_USER_OVERRIDE:-labadmin}" ;;
    *)         die "unknown secret generator '$1'" ;;
  esac
}

# ensure_secrets FILE -> create FILE (mode 600) or add any missing keys.
# Prints how many keys it generated.
ensure_secrets() {
  local file=$1 key gen added=0 new=0 old_umask
  if [ ! -f "$file" ]; then
    new=1
    old_umask=$(umask)
    umask 077
    {
      echo "# Lakehouse Lab secrets. Generated by install.sh; never commit this file."
      echo "# Values are kept on re-install: services were initialised with them."
    } >"$file"
    umask "$old_umask"
  fi
  chmod 600 "$file"
  while read -r key gen; do
    [ -n "$key" ] || continue
    if ! env_has "$file" "$key"; then
      env_set "$file" "$key" "$(gen_value "$gen")"
      added=$((added + 1))
    fi
  done < <(secret_spec)
  chmod 600 "$file"
  if [ "$(stat -c '%a' "$file" 2>/dev/null)" != 600 ]; then
    warn "$file is not mode 600 (filesystem ignores chmod?). Keep it private."
  fi
  if [ "$new" = 1 ]; then
    ok "Generated $file ($added secrets, mode 600)"
  elif [ "$added" -gt 0 ]; then
    ok "Kept existing secrets in $file; added $added new key(s)"
  else
    ok "Kept existing secrets in $file"
  fi
}
