#!/usr/bin/env bash
# Regenerate lock/constraints.txt, the GENERATED transitive-pin lock of the workspace's MCP venv
# (ADR-012 amendment). Run it whenever DBT_MCP_VERSION, MCP_SDK_VERSION, SQLGLOT_VERSION,
# TRINO_PYTHON_VERSION or the workspace's Python base changes, and commit the result.
#
#   v3/images/workspace/mcp/relock.sh
#
# Resolves requirements.in fresh in a throwaway container of the workspace's own base image
# (python:${PYTHON_IMAGE_TAG}@${PYTHON_IMAGE_DIGEST}), freezes it, and drops the top-level
# packages, whose pins live in versions.env.
set -euo pipefail
here=$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)
v3=$(cd -P "$here/../../.." && pwd)
val() { cat "$v3/versions.env" "$v3"/.pins/*.env 2>/dev/null | sed -n "s/^$1=//p" | tail -n 1; }
args=()
for v in PYTHON_IMAGE_TAG PYTHON_IMAGE_DIGEST DBT_MCP_VERSION MCP_SDK_VERSION SQLGLOT_VERSION TRINO_PYTHON_VERSION; do
  x=$(val "$v"); [ -n "$x" ] || { echo "relock: $v has no value in versions.env" >&2; exit 1; }
  printf -v "$v" '%s' "$x"
  args+=(-e "$v=$x")
done
tops=$(sed -e 's/#.*//' -e 's/\[.*//' -e 's/=.*//' "$here/requirements.in" | tr 'A-Z_' 'a-z-' \
  | grep -v '^$' | sed 's/-/[-_.]/g' | paste -sd'|')
frozen=$(docker run --rm "${args[@]}" -e PIP_DISABLE_PIP_VERSION_CHECK=1 -v "$here/requirements.in:/req.in:ro" \
  "python:${PYTHON_IMAGE_TAG}@${PYTHON_IMAGE_DIGEST}" sh -c \
  'python -m venv /v >/dev/null && /v/bin/pip install -q --no-cache-dir -r /req.in >/dev/null && /v/bin/pip check >&2 && /v/bin/pip list --format=freeze')
{
  echo "# GENERATED by images/workspace/mcp/relock.sh: transitive pins for the workspace MCP venv. Do not edit."
  printf '%s\n' "$frozen" | grep -v -i -E "^(${tops})==" | grep -v -E '^(pip|setuptools|wheel)=='
} >"$here/lock/constraints.txt"
echo "images/workspace/mcp/lock/constraints.txt: $(grep -vc '^#' "$here/lock/constraints.txt") pins"
