"""lab_ingest: land a small generated batch of orders in lakehouse.analytics.landing_orders.

No internet: the rows are generated by the job (dags/jobs/ingest.py) and appended through
Trino, as the batch service identity lab-batch (never as the person who triggered the run).
Only engineers and lab admins can trigger it (Airflow's Keycloak authorization).
"""
from datetime import datetime

from airflow.sdk import Param, dag, get_current_context, task

import lab_batch


@dag(dag_id="lab_ingest", schedule=None, start_date=datetime(2026, 1, 1), catchup=False,
     max_active_runs=1, default_args=lab_batch.DEFAULT_ARGS, tags=lab_batch.TAGS,
     params={"rows": Param(25, type="integer", minimum=1, maximum=10000,
                           description="How many generated order rows to land")},
     doc_md=__doc__)
def lab_ingest():
    @task
    def ingest():
        ctx = get_current_context()
        lab_batch.log_trigger(ctx)
        tok, c = lab_batch.batch_token()
        env = lab_batch.job_env({"LAB_BATCH_TOKEN": tok})
        lab_batch.run_python_job("ingest.py", ctx["dag_run"].run_id, str(ctx["params"]["rows"]), env=env)

    ingest()


lab_ingest()
