# Lakehouse Lab Authentication Proxy Configuration
# Generated on: Sat Aug 23 04:37:21 PM EDT 2025

proxy:
  # Service routing
  services:
    superset:
      url: ${SUPERSET_URL}
      auth_type: session_based
      admin_user: ${SUPERSET_ADMIN_USER}
      admin_password: ${SUPERSET_ADMIN_PASSWORD}
      
    airflow:
      url: ${AIRFLOW_URL}
      auth_type: basic_auth
      admin_user: ${AIRFLOW_ADMIN_USER}
      admin_password: ${AIRFLOW_ADMIN_PASSWORD}
      
    jupyter:
      url: ${JUPYTER_URL}
      auth_type: token_based
      token: ${JUPYTER_TOKEN}
      
    vizro:
      url: ${VIZRO_URL}
      auth_type: none  # Vizro doesn't have built-in auth
      
    minio:
      url: ${MINIO_CONSOLE_URL}
      auth_type: basic_auth
      admin_user: ${MINIO_ROOT_USER}
      admin_password: ${MINIO_ROOT_PASSWORD}

  # Access control
  access_control:
    data_viewer:
      allowed_services: [superset, jupyter]
      permissions:
        superset: [view_dashboards, view_charts]
        jupyter: [read_notebooks]
        
    data_analyst:
      allowed_services: [superset, jupyter, vizro]
      permissions:
        superset: [create_dashboards, edit_charts]
        jupyter: [create_notebooks, run_kernels]
        vizro: [view_dashboards, create_charts]
        
    data_engineer:
      allowed_services: [superset, jupyter, vizro, airflow, minio]
      permissions:
        airflow: [view_dags, trigger_dags]
        minio: [read_buckets, write_buckets]
        
    admin:
      allowed_services: ["*"]
      permissions: ["*"]

# Logging and monitoring
logging:
  level: ${LOG_LEVEL:-INFO}
  access_log: true
  audit_log: true
