# Lakehouse Lab Authentication Configuration
# Generated on: Sat Aug 23 04:37:21 PM EDT 2025

auth:
  mode: hybrid
  jwt_secret: ${JWT_SECRET}
  
  # Local authentication (always available)
  local:
    enabled: true
    default_admin_email: ${DEFAULT_ADMIN_EMAIL:-admin@localhost}
    admin_emails: ${ADMIN_EMAILS:-admin@localhost}
    
  # OAuth providers
  oauth:
    google:
      enabled: ${GOOGLE_CLIENT_ID:+true}
      client_id: ${GOOGLE_CLIENT_ID}
      client_secret: ${GOOGLE_CLIENT_SECRET}
      allowed_domains: ${COMPANY_DOMAIN:+[${COMPANY_DOMAIN}]}
      
    microsoft:
      enabled: ${MICROSOFT_CLIENT_ID:+true}
      client_id: ${MICROSOFT_CLIENT_ID}
      client_secret: ${MICROSOFT_CLIENT_SECRET}
      tenant_id: ${MICROSOFT_TENANT_ID:-common}
      
    github:
      enabled: ${GITHUB_CLIENT_ID:+true}
      client_id: ${GITHUB_CLIENT_ID}
      client_secret: ${GITHUB_CLIENT_SECRET}
      allowed_orgs: ${GITHUB_ALLOWED_ORGS:+[${GITHUB_ALLOWED_ORGS}]}

  # Role mapping rules
  role_mapping:
    default_role: data_viewer
    admin_emails: ${ADMIN_EMAILS:-admin@localhost}
    company_domain: ${COMPANY_DOMAIN:-}
    
    # Role assignment rules
    rules:
      - condition: email_in_admin_list
        role: admin
      - condition: email_domain_matches_company
        role: data_analyst
      - condition: default
        role: data_viewer

# Security settings
security:
  session:
    duration_hours: 24
    refresh_enabled: true
    
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    
  audit:
    enabled: true
    log_level: info
