#!/usr/bin/env bash
# Regenerate lock/constraints.txt, the GENERATED transitive-pin lock of the Superset image
# (ADR-012 amendment). Run it whenever SUPERSET_VERSION, SUPERSET_IMAGE_DIGEST or one of the
# requirements.in pins changes in versions.env, and commit the result. It builds with an
# empty lock, freezes Superset's venv and drops the top-level packages of requirements.in,
# whose pins live in versions.env. The upstream image's own packages are included on
# purpose: the lock then also fails the build if the base image's venv changes underneath.
#
#   v3/images/superset/relock.sh
#
# Builds through `docker compose` (like the lab itself), so it works without buildx.
set -euo pipefail
here=$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)
v3=$(cd -P "$here/../.." && pwd)
name=$(basename "$here")
tag="lakehouse-lab/v3-${name}:relock"

ctx=$(mktemp -d)
trap 'rm -rf "$ctx"' EXIT
cp -R "$here/." "$ctx/image/"
: >"$ctx/image/lock/constraints.txt"

# Every ARG the Dockerfile declares, valued from versions.env (and pending .pins/*.env).
{
  echo "services:"
  echo "  relock:"
  echo "    image: ${tag}"
  echo "    build:"
  echo "      context: ./image"
  printf '      additional_contexts:\n        config: %s\n' "$v3/config/superset"
  echo "      args:"
  sed -n 's/^[[:space:]]*ARG[[:space:]]\+\([A-Za-z_][A-Za-z0-9_]*\).*/\1/p' "$here/Dockerfile" | sort -u |
    while read -r arg; do
      val=$(cat "$v3/versions.env" "$v3"/.pins/*.env 2>/dev/null | sed -n "s/^${arg}=//p" | tail -n 1)
      [ -n "$val" ] || { echo "relock: ARG $arg has no value in versions.env" >&2; exit 1; }
      printf '        %s: "%s"\n' "$arg" "$val"
    done
} >"$ctx/compose.yaml"
docker compose -p "v3-relock-${name}" -f "$ctx/compose.yaml" build -q relock

tops=$(sed -e 's/#.*//' -e 's/\[.*//' -e 's/=.*//' "$here/requirements.in" | tr 'A-Z_' 'a-z-' \
  | grep -v '^$' | sed 's/-/[-_.]/g' | paste -sd'|')
{
  echo "# GENERATED by images/${name}/relock.sh: transitive pins for the ${name} image. Do not edit."
  docker run --rm --network none -e UV_NO_CACHE=1 --entrypoint uv "$tag" pip freeze --python /app/.venv/bin/python \
    | grep -v -i -E "^(${tops})==" | grep -v -E '^(pip|setuptools|wheel)==' | grep -v -E '^(-e |.* @ )'
} >"$here/lock/constraints.txt"
docker image rm "$tag" >/dev/null
echo "images/${name}/lock/constraints.txt: $(grep -vc '^#' "$here/lock/constraints.txt") pins"
