"""AI gateway key broker and admin client (CONTRACT Phase 5, GATEWAY). Python stdlib only.

The ai-gateway (LiteLLM proxy, compose/ai.yaml) holds the provider keys and per-user budgets.
Only two services ever hold its master key: the gateway itself and this broker (`ai-keys`,
`python3 -m bootstrap.ai_gateway serve`, on the bootstrap image). JupyterHub never sees the
master key: it calls the broker with its own bootstrap-created credential
AI_GATEWAY_HUB_TOKEN (.secrets.env, generated by the installer), and the broker can do exactly
three things for it: mint (= rotate) a user's key, revoke a user's keys, report status.

Broker HTTP interface (on the `lab` network; http://ai-keys:8080):

  Every /v1/ call needs  Authorization: Bearer $AI_GATEWAY_HUB_TOKEN
  POST /v1/keys/mint    {"user": "<jupyterhub username>"}
  POST /v1/keys/rotate  same as mint
        -> 200 {"user", "key": "sk-...", "base_url": "http://ai-gateway:4000",
                "openai_base_url": "http://ai-gateway:4000/v1", "model": "lab-default",
                "models": [...], "configured": bool, "message": str|null,
                "max_budget": float, "budget_duration": "30d", "rpm_limit": int,
                "key_expires": "30d"}
           Creates the gateway user if missing (role internal_user_viewer: inference and its
           own spend only, no key management), reconciles its budget with the lab settings,
           creates a NEW key and deletes the user's previous lab keys. So a mint on every
           spawn is the intended use; the key is shown only in this response (the gateway
           stores a hash). Spend and budget belong to the USER, so rotating never resets them.
           `configured: false` (no provider enabled) still returns a key: requests then get
           "AI isn't configured; ask your lab admin." and enabling a provider later needs no
           new key.
  POST /v1/keys/revoke  {"user": "..."} -> 200 {"user", "revoked": n}
  GET  /v1/status       -> 200 {"gateway": "ok", "configured", "models", "budget": {...}}
  GET  /healthz         -> 200 {"ok": true} (no auth; the compose healthcheck)
  Errors: 400 bad request / invalid user, 401 missing or wrong token, 503 gateway down.
  Bodies are JSON; the key is never logged.

Budget settings (environment of ai-keys; from .env):
  LAB_AI_USER_BUDGET_USD  per-user budget per period (default 5)
  LAB_AI_BUDGET_DURATION  budget period (default 30d)
  LAB_AI_USER_RPM         requests per minute per user (default 30)
  LAB_AI_KEY_DURATION     key lifetime (default 30d; a spawn mints a fresh one)
At start the broker reconciles every lab-managed gateway user with these values, so a
changed budget applies to everyone at the next `up`.

CLI (used by `./lab ai status` and the tests, inside the ai-keys container):
  python3 -m bootstrap.ai_gateway serve | status | mint USER | revoke USER
"""
import hmac
import json
import os
import re
import sys
import time
import urllib.parse
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

from . import web

GATEWAY_URL = os.environ.get("AI_GATEWAY_URL", "http://ai-gateway:4000")
KEY_ALIAS_PREFIX = "lab-ws:"
USER_ROLE = "internal_user_viewer"
# JupyterHub usernames as the lab creates them (Keycloak preferred_username, lower-cased).
USER_RE = re.compile(r"^[a-z0-9][a-z0-9._@-]{0,63}$")
NOT_CONFIGURED = "AI isn't configured; ask your lab admin."
MAX_BODY = 4096


class GatewayError(RuntimeError):
    """The gateway is unreachable or answered unexpectedly."""


def settings(env=None):
    env = os.environ if env is None else env

    def num(name, default, cast):
        raw = (env.get(name) or "").strip()
        try:
            v = cast(raw) if raw else cast(default)
        except ValueError:
            raise SystemExit(f"[ai-keys] {name}={raw!r} is not a number")
        if v < 0:
            raise SystemExit(f"[ai-keys] {name} must be >= 0")
        return v

    def duration(name, default):
        v = (env.get(name) or "").strip() or default
        if not re.fullmatch(r"\d+[smhd]|\d+mo", v):
            raise SystemExit(f"[ai-keys] {name}={v!r}: use e.g. 30d, 7d, 24h")
        return v

    return {"max_budget": num("LAB_AI_USER_BUDGET_USD", 5, float),
            "budget_duration": duration("LAB_AI_BUDGET_DURATION", "30d"),
            "rpm_limit": num("LAB_AI_USER_RPM", 30, int),
            "key_duration": duration("LAB_AI_KEY_DURATION", "30d")}


def valid_user(user):
    return isinstance(user, str) and bool(USER_RE.fullmatch(user))


class Gateway:
    """The LiteLLM admin API, with the master key. Only management and metadata endpoints are
    used: never /health (it sends a real request to every model) nor a model call."""

    def __init__(self, master_key, url=GATEWAY_URL, request=web.request):
        self.url = url.rstrip("/")
        self.h = {"Authorization": f"Bearer {master_key}"}
        self._request = request

    def _call(self, method, path, body=None, expect=(200,)):
        try:
            _, data, _ = self._request(method, self.url + path, json_body=body, headers=self.h,
                                       expect=expect, timeout=30)
        except web.HTTPError as e:
            raise GatewayError(f"{method} {path} -> HTTP {e.status}") from None
        except OSError as e:
            raise GatewayError(f"{method} {path}: {e}") from None
        return data

    def alive(self):
        try:
            self._call("GET", "/health/liveliness")
            return True
        except GatewayError:
            return False

    def wait(self, timeout=300):
        deadline = time.time() + timeout
        while time.time() < deadline:
            if self.alive():
                return
            time.sleep(2)
        raise GatewayError(f"{self.url} not alive after {timeout}s")

    def models(self):
        data = self._call("GET", "/v1/models") or {}
        return sorted(m["id"] for m in data.get("data", []) if isinstance(m, dict) and "id" in m)

    def get_user(self, user):
        try:
            data = self._call("GET", "/user/info?" + urllib.parse.urlencode({"user_id": user}),
                              expect=(200,))
        except GatewayError as e:
            if "HTTP 404" in str(e):
                return None
            raise
        return (data or {}).get("user_info")

    def ensure_user(self, user, cfg):
        """-> 'created' | 'updated' | 'unchanged'. Budget/role follow the lab settings."""
        want = {"max_budget": cfg["max_budget"], "budget_duration": cfg["budget_duration"],
                "rpm_limit": cfg["rpm_limit"], "user_role": USER_ROLE}
        cur = self.get_user(user)
        if cur is None:
            self._call("POST", "/user/new", dict(want, user_id=user, auto_create_key=False,
                                                 send_invite_email=False,
                                                 metadata={"lab_managed": True}))
            return "created"
        diff = {k: v for k, v in want.items() if cur.get(k) != v}
        if not (cur.get("metadata") or {}).get("lab_managed"):
            diff["metadata"] = dict(cur.get("metadata") or {}, lab_managed=True)
        if not diff:
            return "unchanged"
        self._call("POST", "/user/update", dict(diff, user_id=user))
        return "updated"

    def lab_keys(self, user):
        """Token hashes of the user's lab-minted keys (alias lab-ws:<user>:...)."""
        q = urllib.parse.urlencode({"user_id": user, "return_full_object": "true", "size": 100})
        data = self._call("GET", "/key/list?" + q) or {}
        out = []
        for k in data.get("keys", []):
            if isinstance(k, dict) and str(k.get("key_alias") or "").startswith(f"{KEY_ALIAS_PREFIX}{user}:") \
                    and k.get("user_id") == user and k.get("token"):
                out.append(k["token"])
        return out

    def generate_key(self, user, cfg):
        data = self._call("POST", "/key/generate", {
            "user_id": user,
            "key_alias": f"{KEY_ALIAS_PREFIX}{user}:{int(time.time() * 1000)}",
            "duration": cfg["key_duration"],
            "metadata": {"lab_managed": True, "lab_user": user}})
        key = (data or {}).get("key")
        if not (isinstance(key, str) and key.startswith("sk-")):
            raise GatewayError("POST /key/generate returned no key")
        return key

    def delete_keys(self, tokens):
        if tokens:
            self._call("POST", "/key/delete", {"keys": list(tokens)})
        return len(tokens)

    def lab_users(self):
        users, page = [], 1
        while True:
            data = self._call("GET", "/user/list?" + urllib.parse.urlencode({"page": page, "page_size": 100})) or {}
            batch = data.get("users") or []
            users += [u for u in batch if isinstance(u, dict) and (u.get("metadata") or {}).get("lab_managed")]
            if len(batch) < 100:
                return users
            page += 1


# ---------------------------------------------------------------- operations
def mint(gw, user, cfg):
    if not valid_user(user):
        raise ValueError("invalid user")
    gw.ensure_user(user, cfg)
    old = gw.lab_keys(user)
    key = gw.generate_key(user, cfg)
    gw.delete_keys(old)
    models = gw.models()
    configured = bool(models)
    return {"user": user, "key": key,
            "base_url": GATEWAY_URL, "openai_base_url": GATEWAY_URL + "/v1",
            "model": "lab-default", "models": models, "configured": configured,
            "message": None if configured else NOT_CONFIGURED,
            "max_budget": cfg["max_budget"], "budget_duration": cfg["budget_duration"],
            "rpm_limit": cfg["rpm_limit"], "key_expires": cfg["key_duration"]}


def revoke(gw, user):
    if not valid_user(user):
        raise ValueError("invalid user")
    return {"user": user, "revoked": gw.delete_keys(gw.lab_keys(user))}


def status(gw, cfg):
    try:
        models = gw.models()
    except GatewayError as e:
        return {"gateway": f"unavailable ({e})", "configured": False, "models": [], "budget": cfg}
    return {"gateway": "ok", "configured": bool(models), "models": models,
            "message": None if models else NOT_CONFIGURED, "budget": cfg}


def reconcile(gw, cfg):
    """Every lab-managed gateway user gets the current budget settings. -> counts."""
    counts = {"updated": 0, "unchanged": 0}
    for u in gw.lab_users():
        counts[gw.ensure_user(u["user_id"], cfg)] += 1
    return counts


# ---------------------------------------------------------------- HTTP server
def make_handler(gw, cfg, hub_token):
    if not hub_token or len(hub_token) < 32:
        raise SystemExit("[ai-keys] AI_GATEWAY_HUB_TOKEN is missing or too short; run install.sh")
    expected = f"Bearer {hub_token}".encode()

    class Handler(BaseHTTPRequestHandler):
        server_version = "lab-ai-keys/1"
        protocol_version = "HTTP/1.1"

        def log_message(self, fmt, *args):  # method, path and status only; never bodies
            pass

        def _send(self, status_code, obj):
            data = json.dumps(obj).encode()
            self.send_response(status_code)
            self.send_header("Content-Type", "application/json")
            self.send_header("Cache-Control", "no-store")
            self.send_header("Content-Length", str(len(data)))
            self.end_headers()
            self.wfile.write(data)
            print(f"[ai-keys] {self.command} {self.path.split('?')[0]} -> {status_code}", flush=True)

        def _authorized(self):
            got = (self.headers.get("Authorization") or "").encode()
            return hmac.compare_digest(got, expected)

        def do_GET(self):
            if self.path == "/healthz":
                return self._send(200, {"ok": True})
            if self.path == "/v1/status":
                if not self._authorized():
                    return self._send(401, {"error": "unauthorized"})
                return self._send(200, status(gw, cfg))
            return self._send(404, {"error": "not found"})

        def do_POST(self):
            routes = {"/v1/keys/mint": mint, "/v1/keys/rotate": mint, "/v1/keys/revoke": revoke}
            op = routes.get(self.path)
            if op is None:
                return self._send(404, {"error": "not found"})
            if not self._authorized():
                return self._send(401, {"error": "unauthorized"})
            try:
                n = int(self.headers.get("Content-Length") or 0)
            except ValueError:
                n = -1
            if n < 0 or n > MAX_BODY:
                return self._send(400, {"error": "bad request"})
            try:
                body = json.loads(self.rfile.read(n) or b"{}")
            except ValueError:
                return self._send(400, {"error": "bad request: invalid JSON"})
            user = body.get("user") if isinstance(body, dict) else None
            if not valid_user(user):
                return self._send(400, {"error": "bad request: invalid user"})
            try:
                result = op(gw, user, cfg) if op is mint else op(gw, user)
            except GatewayError as e:
                print(f"[ai-keys] gateway error: {e}", file=sys.stderr, flush=True)
                return self._send(503, {"error": "AI gateway unavailable"})
            return self._send(200, result)

    return Handler


def serve():
    cfg = settings()
    gw = Gateway(os.environ["LITELLM_MASTER_KEY"])
    handler = make_handler(gw, cfg, os.environ.get("AI_GATEWAY_HUB_TOKEN", ""))
    print(f"[ai-keys] waiting for {GATEWAY_URL}", flush=True)
    gw.wait()
    counts = reconcile(gw, cfg)
    print(f"[ai-keys] budget {cfg['max_budget']} USD / {cfg['budget_duration']}, "
          f"{cfg['rpm_limit']} rpm; lab users: {counts['updated']} updated, "
          f"{counts['unchanged']} unchanged; models: {', '.join(gw.models()) or 'none (AI not configured)'}",
          flush=True)
    srv = ThreadingHTTPServer(("0.0.0.0", int(os.environ.get("AI_KEYS_PORT", "8080"))), handler)
    srv.daemon_threads = True
    srv.serve_forever()


def main(argv):
    cmd = argv[1] if len(argv) > 1 else ""
    if cmd == "serve":
        return serve()
    gw = Gateway(os.environ["LITELLM_MASTER_KEY"])
    cfg = settings()
    if cmd == "status":
        print(json.dumps(status(gw, cfg), indent=2, sort_keys=True))
        return 0
    if cmd in ("mint", "revoke") and len(argv) == 3:
        out = mint(gw, argv[2], cfg) if cmd == "mint" else revoke(gw, argv[2])
        print(json.dumps(out, indent=2, sort_keys=True))
        return 0
    print("usage: python3 -m bootstrap.ai_gateway serve | status | mint USER | revoke USER", file=sys.stderr)
    return 2


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv))
    except (GatewayError, ValueError) as e:
        print(f"[ai-keys] {e}", file=sys.stderr)
        sys.exit(1)
