"""OQ-17: Trino file group provider, generated from Keycloak group membership.

Format (Trino `group-provider.name=file`): one line per group, `group:user1,user2`.
Trino re-reads the file every `file.refresh-period`. The file only changes when membership
changed, and is replaced atomically.
"""
import os

PATH = "/var/lib/lab/trino-groups/groups.txt"


def render(members_by_group):
    lines = ["# GENERATED by bootstrap from Keycloak realm 'lakehouse'. Do not edit."]
    for group in sorted(members_by_group):
        users = members_by_group[group]
        if users:
            lines.append(f"{group}:{','.join(sorted(users))}")
    return "\n".join(lines) + "\n"


def write(members_by_group, path=PATH):
    """Returns True if the file changed."""
    content = render(members_by_group)
    try:
        with open(path, encoding="utf-8") as f:
            if f.read() == content:
                return False
    except FileNotFoundError:
        pass
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(content)
    os.chmod(tmp, 0o644)
    os.replace(tmp, path)
    return True
