#!/usr/bin/env bash
# Regenerate the GENERATED transitive-pin locks of the Airflow image (ADR-012 amendment):
#   lock/constraints.txt       Airflow's environment (base image + the Keycloak provider)
#   lock/jobs-constraints.txt  the /opt/lab/jobs virtualenv (dbt, Trino, papermill, Spark client)
# Run it whenever an Airflow or jobs pin in versions.env changes, and commit the result. It
# resolves requirements fresh (empty locks), freezes both environments, and drops the
# top-level packages whose pins live in versions.env (lines with ==${VAR}).
#
#   v3/images/airflow/relock.sh
#
# Builds through `docker compose` (like the lab itself), so it works without buildx.
set -euo pipefail
here=$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)
v3=$(cd -P "$here/../.." && pwd)
name=$(basename "$here")
tag="lakehouse-lab/v3-${name}:relock"

ctx=$(mktemp -d)
trap 'rm -rf "$ctx"' EXIT
cp -R "$here/." "$ctx/image/"
: >"$ctx/image/lock/constraints.txt"
: >"$ctx/image/lock/jobs-constraints.txt"

# Every ARG the Dockerfile declares, valued from versions.env (and pending .pins/*.env).
shopt -s nullglob
pins=("$v3/versions.env" "$v3"/.pins/*.env)
{
  echo "services:"
  echo "  relock:"
  echo "    image: ${tag}"
  echo "    build:"
  echo "      context: ./image"
  echo "      args:"
  sed -n 's/^[[:space:]]*ARG[[:space:]]\+\([A-Za-z_][A-Za-z0-9_]*\).*/\1/p' "$here/Dockerfile" | sort -u |
    while read -r arg; do
      val=$(cat "${pins[@]}" | sed -n "s/^${arg}=//p" | tail -n 1)
      [ -n "$val" ] || { echo "relock: ARG $arg has no value in versions.env" >&2; exit 1; }
      printf '        %s: "%s"\n' "$arg" "$val"
    done
} >"$ctx/compose.yaml"
docker compose -p "v3-relock-${name}" -f "$ctx/compose.yaml" build -q relock

# tops FILE -> regex of the package names pinned with ==${VAR} in FILE
tops() {
  grep -E '==\$\{' "$1" | sed -e 's/\[.*//' -e 's/=.*//' | tr 'A-Z_' 'a-z-' | sed 's/-/[-_.]/g' | paste -sd'|'
}
freeze() { # PYTHON REQFILE LOCKFILE LABEL
  {
    echo "# GENERATED by images/${name}/relock.sh: transitive pins for the ${name} image ($4). Do not edit."
    docker run --rm --network none --entrypoint "$1" "$tag" -m pip list --format=freeze \
      | grep -v -i -E "^($(tops "$2"))==" | grep -v -E '^(pip|setuptools|wheel)=='
  } >"$3"
  echo "images/${name}/${3#"$here"/}: $(grep -vc '^#' "$3") pins"
}
freeze /home/airflow/.local/bin/python "$here/requirements.in" "$here/lock/constraints.txt" "Airflow environment"
freeze /opt/lab/jobs/bin/python "$here/jobs-requirements.in" "$here/lock/jobs-constraints.txt" "jobs venv"
docker image rm "$tag" >/dev/null
