"""E1 checkpoint: are the three shipment files in your Iceberg table, typed and partitioned?

Run it with `lab-tracks check E1` (or `python checkpoint.py`). It looks at the RESULT only,
as you, through Trino: it does not read your notebook.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "_shared"))
sys.path.insert(0, HERE)

from trackcheck import Checkpoint, Fail, Trino, namespace  # noqa: E402

import make_data  # noqa: E402

TABLE = "shipments"
WANT_TYPES = {
    "shipment_id": ("bigint",),
    "orderkey": ("bigint",),
    "carrier": ("varchar",),
    "shipped_at": ("timestamp(6) with time zone", "timestamp(6)"),
    "weight_kg": ("double",),
    "status": ("varchar",),
}

cp = Checkpoint("E1", "Files to Iceberg with Spark")
S = {}


@cp.check("your namespace exists")
def _namespace():
    S["trino"], S["ns"] = Trino(), namespace()
    if not S["trino"].schema_exists(S["ns"]):
        raise Fail(f"lakehouse.{S['ns']} does not exist",
                   f"Run step 4 of the lesson: spark.sql(\"CREATE NAMESPACE IF NOT EXISTS lakehouse.{S['ns']}\")")
    return f"lakehouse.{S['ns']}"


@cp.check("the shipments table exists")
def _table():
    if not S["trino"].table_exists(S["ns"], TABLE):
        raise Fail(f"no table lakehouse.{S['ns']}.{TABLE}",
                   "Run step 5 (CREATE TABLE ... USING iceberg). Check the spelling: the table "
                   "must be called `shipments`.")
    return f"lakehouse.{S['ns']}.{TABLE}"


@cp.check("columns have real types (not all strings)")
def _types():
    cols = S["trino"].columns(S["ns"], TABLE)
    missing = [c for c in WANT_TYPES if c not in cols]
    if missing:
        raise Fail(f"missing column(s): {', '.join(missing)}; the table has {', '.join(cols)}",
                   "Recreate the table with the schema from step 5 (drop it first with a plain "
                   "DROP TABLE, then create it again).")
    wrong = {c: cols[c] for c, ok in WANT_TYPES.items() if cols[c] not in ok}
    if wrong:
        detail = ", ".join(f"{c} is {t} (want {WANT_TYPES[c][0]})" for c, t in wrong.items())
        raise Fail(detail,
                   "CSV files carry no types: everything is text until you convert it. Use the "
                   "explicit schema from step 5 and convert the pandas columns before "
                   "createDataFrame (step 6).")
    return ", ".join(f"{c} {t}" for c, t in cols.items())


@cp.check("the table is partitioned by day of shipped_at")
def _partitioning():
    ddl = S["trino"].one(f'SHOW CREATE TABLE lakehouse."{S["ns"]}"."{TABLE}"') or ""
    if "day(shipped_at)" not in ddl.replace('"', ""):
        raise Fail("no day(shipped_at) partitioning in the table definition",
                   "Add PARTITIONED BY (days(shipped_at)) to CREATE TABLE (step 5). Partitioning "
                   "is part of the table definition, so recreate the table and load again.")
    return "partitioning = day(shipped_at)"


@cp.check("all three files are loaded, each exactly once")
def _rows():
    want = make_data.expected()
    n, distinct, weight, days = S["trino"].rows(
        f'SELECT count(*), count(DISTINCT shipment_id), round(coalesce(sum(weight_kg), 0), 2), '
        f'count(DISTINCT CAST(shipped_at AS date)) FROM lakehouse."{S["ns"]}"."{TABLE}"')[0]
    if n != distinct:
        raise Fail(f"{n} rows but only {distinct} different shipment ids: some rows are there twice",
                   "A file was loaded more than once. See 'Common mistakes' in the lesson: delete "
                   "the table's rows (DELETE FROM ...) and load each file once.")
    if n != want["rows"]:
        raise Fail(f"{n} rows, want {want['rows']} ({want['days']} files of "
                   f"{make_data.ROWS_PER_DAY})",
                   "Load all three files (step 8). A table with 400 rows has only the first day.")
    if abs(float(weight) - want["weight_kg"]) > 0.05:
        raise Fail(f"total weight_kg is {weight}, want {want['weight_kg']}",
                   "The values changed on the way in. Load the files as generated by make_data.py "
                   "and convert weight_kg with pd.to_numeric / astype(float).")
    if days != want["days"]:
        raise Fail(f"shipped_at covers {days} day(s), want {want['days']}",
                   "Convert shipped_at with pd.to_datetime before loading (step 6).")
    return f"{n} rows, {distinct} shipments, {days} days, total weight {weight} kg"


@cp.check("one partition per day")
def _partitions():
    parts = S["trino"].one(f'SELECT count(*) FROM lakehouse."{S["ns"]}"."{TABLE}$partitions"')
    if parts != 3:
        raise Fail(f"{parts} partitions, want 3", "Partition by days(shipped_at), not by hours "
                   "or by the raw timestamp.")
    return "3 partitions"


if __name__ == "__main__":
    sys.exit(cp.run())
