name: Credential Rotation Reminder

on:
  schedule:
    - cron: '0 9 1 * *' # 9:00 UTC on the 1st of every month
  workflow_dispatch:

jobs:
  credential-rotation-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check credential files for age
        id: check_age
        run: |
          # List of credential files to check
          files=".env scripts/credentials.env secrets/.env secrets/credentials.json"
          threshold_days=30
          now=$(date +%s)
          oldest=0
          found=0
          for f in $files; do
            if [ -f "$f" ]; then
              found=1
              mtime=$(stat -c %Y "$f")
              age_days=$(( (now - mtime) / 86400 ))
              if [ "$age_days" -gt "$oldest" ]; then
                oldest=$age_days
              fi
            fi
          done
          if [ "$found" -eq 0 ]; then
            echo "No credential files found to check."
            echo "rotation_due=false" >> $GITHUB_OUTPUT
          elif [ "$oldest" -ge "$threshold_days" ]; then
            echo "Credentials older than $threshold_days days detected."
            echo "rotation_due=true" >> $GITHUB_OUTPUT
          else
            echo "All credentials are recent."
            echo "rotation_due=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub issue reminder
        if: steps.check_age.outputs.rotation_due == 'true'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Credential Rotation Reminder"
          content-filepath: .github/credential-rotation-reminder.md
          labels: security, credentials, reminder

      - name: Output reminder if not creating issue
        if: steps.check_age.outputs.rotation_due != 'true'
        run: echo "No credential rotation needed at this time."