# .github/workflows/shellcheck.yml
name: Shell Script Linting
on: [push, pull_request]
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: '.'
          ignore_paths: 'lakehouse-lab_backup_* lakehouse-lab'
        env:
          SHELLCHECK_OPTS: -e SC2034 -e SC2086 -e SC2155 -e SC1091 -e SC2076 -e SC2162 -e SC2129 -e SC2005 -e SC2126 -e SC2154 -e SC2329
