# .github/workflows/startup-test.yml
name: Service Startup Test
on: [push, pull_request]
jobs:
  startup-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate test credentials
        run: |
          # Create minimal .env file with secure credentials
          ./scripts/generate-credentials.sh

          # Override with test-specific settings
          echo "COMPOSE_PROJECT_NAME=lakehouse-test" >> .env
          echo "HOST_IP=localhost" >> .env

      - name: Create named volumes for test
        run: |
          # Create required named volumes for testing
          docker volume create lakehouse-test_postgres_data
          docker volume create lakehouse-test_minio_data

      - name: Test basic service startup
        run: |
          # Start core services only
          docker compose up -d postgres minio lakehouse-init
          
          # Wait longer for services to be ready
          echo "Waiting for services to start..."
          sleep 60
          
          # Show running containers for debugging
          docker compose ps
          
          # Check health endpoints with retry
          echo "Testing MinIO health endpoint..."
          for i in {1..10}; do
            if curl -f http://localhost:9000/minio/health/live; then
              echo "MinIO health check passed"
              break
            fi
            echo "MinIO health check failed, attempt $i/10"
            sleep 5
          done

          # Check PostgreSQL is accessible with retry
          echo "Testing PostgreSQL connection..."
          for i in {1..10}; do
            if docker compose exec -T postgres pg_isready -U postgres; then
              echo "PostgreSQL connection successful"
              break
            fi
            echo "PostgreSQL connection failed, attempt $i/10"
            sleep 5
          done

          # Show logs if there are issues
          echo "Service logs:"
          docker compose logs --tail=20

          # Cleanup
          docker compose down -v
          docker volume rm lakehouse-test_postgres_data lakehouse-test_minio_data || true
