# .github/workflows/startup-test.yml
name: Service Startup Test
on: [push, pull_request]
jobs:
  startup-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate test credentials
        run: |
          # Create minimal .env file with secure credentials
          ./scripts/generate-credentials.sh

          # Override with test-specific settings
          echo "COMPOSE_PROJECT_NAME=lakehouse-test" >> .env
          echo "HOST_IP=localhost" >> .env

      - name: Create named volumes for test
        run: |
          # Create required named volumes for testing
          docker volume create lakehouse-test_postgres_data
          docker volume create lakehouse-test_minio_data

      - name: Test basic service startup
        run: |
          # Test docker compose configuration validation only
          echo "Validating docker-compose configuration..."
          docker compose config > /dev/null
          echo "✅ Docker compose configuration is valid"

          # Test that services are properly defined
          echo "Checking service definitions..."
          services=$(docker compose config --services)
          echo "Available services: $services"
          
          # Check that core services are defined
          if echo "$services" | grep -q "postgres"; then
            echo "✅ PostgreSQL service defined"
          else
            echo "❌ PostgreSQL service not found"
            exit 1
          fi
          
          if echo "$services" | grep -q "minio"; then
            echo "✅ MinIO service defined"  
          else
            echo "❌ MinIO service not found"
            exit 1
          fi
          
          if echo "$services" | grep -q "lakehouse-init"; then
            echo "✅ Lakehouse init service defined"
          else
            echo "❌ Lakehouse init service not found"  
            exit 1
          fi
          
          echo "✅ All core services properly defined"
